[namespace]
name = "microsoft"
registry = "ghcr.io/microsoft"

[[component]]
name = "fetch-rs"
repository = "fetch-rs"

[[component]]
name = "eval-py"
repository = "eval-py"

[[component]]
name = "filesystem-rs"
repository = "filesystem-rs"

[[component]]
name = "get-weather-js"
repository = "get-weather-js"

[[component]]
name = "gomodule-go"
repository = "gomodule-go"

[[component]]
name = "time-server-js"
repository = "time-server-js"

[[component]]
name = "arxiv-rs"
repository = "arxiv-rs"

[[component]]
name = "github-js"
repository = "github-js"

[[component]]
name = "memory-js"
repository = "memory-js"

[[component]]
name = "brave-search-rs"
repository = "brave-search-rs"

[[component]]
name = "context7-rs"
repository = "context7-rs"

[[component]]
name = "get-open-meteo-weather-js"
repository = "get-open-meteo-weather-js"
